name: Continuous Integration

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Check uv.lock file
        run: uv lock --check

      - name: Install project
        run: uv sync --all-extras --dev

      - name: Ruff check with linter
        run: uvx ruff check --no-fix

      - name: Ruff check with formatter
        run: uvx ruff format --check

      - name: Run tests
        run: uv run pytest -s -v tests

      - name: Test package build
        run: uv build